name: Deploy website

on:
  push:
    branches:
      - main
      - develop

env:
  BRANCH_NAME: ${{ github.ref_name }}

jobs:
  build-and-deploy: 
    runs-on: ubuntu-latest
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install Netlify CLI
        run: npm install netlify-cli@17.10.1 -g

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        env:
          VITE_TEST: ${{ env.VITE_TEST }} # Use environment variable      
        run: npm run build

      - name: Create _redirects File
        run: echo '/* /index.html 200' > dist/_redirects

      - name: Deploy to Netlify
        id: netlify_deploy
        run: |
          deploy_flag=""
          if [ "$BRANCH_NAME" = "main" ]; then
            deploy_flag="--prod"
          elif [ "$BRANCH_NAME" = "develop" ]; then
            deploy_flag="--alias staging"
          fi
          netlify deploy \
            --dir dist \
            --site ${{ secrets.NETLIFY_SITE_ID }} \
            --auth ${{ secrets.NETLIFY_API_TOKEN }} \
            $deploy_flag
